/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package agoravai;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        AppTest classUnderTest = new AppTest();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
